LIBRARY := SUHH2core
DICT := include/AnalysisModuleRunner.h include/NtupleObjects.h include/SUHH2core_LinkDef.h

USERLDFLAGS := -Wl,-rpath,/afs/desy.de/user/p/peiffer/www/FastJet/lib -lm -L/afs/desy.de/user/p/peiffer/www/FastJet/lib -lfastjettools -lfastjet -lHOTVR -lNsubjettiness -lRecursiveTools
USERCXXFLAGS := -I/afs/desy.de/user/p/peiffer/www/FastJet/include

TEST := 1
TESTPAR := 1
include ../Makefile.common
