LIBRARY := SUHH2core
DICT := include/AnalysisModuleRunner.h include/NtupleObjects.h include/SUHH2core_LinkDef.h

USERLDFLAGS := -Wl,-rpath,/nfs/dust/cms/user/froehlia/CMSSW_8_0_20/src/FastJet/lib -lm -L/nfs/dust/cms/user/froehlia/CMSSW_8_0_20/src/FastJet/lib -lfastjettools -lfastjet -lHOTVR -lNsubjettiness -lRecursiveTools
USERCXXFLAGS := -I/nfs/dust/cms/user/froehlia/CMSSW_8_0_20/src/FastJet/include

TEST := 1
TESTPAR := 1
include ../Makefile.common
