LIBRARY := SUHH2common
DICT := include/ReconstructionHypothesis.h include/SUHH2common_LinkDef.h
TEST := 1
USERLDFLAGS := -lSUHH2core -lSUHH2JetMETObjects -lMinuit -lGenVector
include ../Makefile.common
